#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionDatabase.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertCreditResults(CreditResults instance);
    partial void UpdateCreditResults(CreditResults instance);
    partial void DeleteCreditResults(CreditResults instance);
    partial void InsertExamResults(ExamResults instance);
    partial void UpdateExamResults(ExamResults instance);
    partial void DeleteExamResults(ExamResults instance);
    partial void InsertExams(Exams instance);
    partial void UpdateExams(Exams instance);
    partial void DeleteExams(Exams instance);
    partial void InsertCredits(Credits instance);
    partial void UpdateCredits(Credits instance);
    partial void DeleteCredits(Credits instance);
    partial void InsertStudents(Students instance);
    partial void UpdateStudents(Students instance);
    partial void DeleteStudents(Students instance);
    partial void InsertGroups(Groups instance);
    partial void UpdateGroups(Groups instance);
    partial void DeleteGroups(Groups instance);
    partial void InsertProfessors(Professors instance);
    partial void UpdateProfessors(Professors instance);
    partial void DeleteProfessors(Professors instance);
    partial void InsertDisciplines(Disciplines instance);
    partial void UpdateDisciplines(Disciplines instance);
    partial void DeleteDisciplines(Disciplines instance);
    partial void InsertSessionsInfo(SessionsInfo instance);
    partial void UpdateSessionsInfo(SessionsInfo instance);
    partial void DeleteSessionsInfo(SessionsInfo instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::SessionDatabase.Properties.Settings.Default.DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CreditResults> CreditResults
		{
			get
			{
				return this.GetTable<CreditResults>();
			}
		}
		
		public System.Data.Linq.Table<ExamResults> ExamResults
		{
			get
			{
				return this.GetTable<ExamResults>();
			}
		}
		
		public System.Data.Linq.Table<Exams> Exams
		{
			get
			{
				return this.GetTable<Exams>();
			}
		}
		
		public System.Data.Linq.Table<Credits> Credits
		{
			get
			{
				return this.GetTable<Credits>();
			}
		}
		
		public System.Data.Linq.Table<Students> Students
		{
			get
			{
				return this.GetTable<Students>();
			}
		}
		
		public System.Data.Linq.Table<Groups> Groups
		{
			get
			{
				return this.GetTable<Groups>();
			}
		}
		
		public System.Data.Linq.Table<Professors> Professors
		{
			get
			{
				return this.GetTable<Professors>();
			}
		}
		
		public System.Data.Linq.Table<Disciplines> Disciplines
		{
			get
			{
				return this.GetTable<Disciplines>();
			}
		}
		
		public System.Data.Linq.Table<SessionsInfo> SessionsInfo
		{
			get
			{
				return this.GetTable<SessionsInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CreditResults")]
	public partial class CreditResults : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CreditMarkId;
		
		private long _StudentId;
		
		private long _CreditId;
		
		private bool _Result;
		
		private EntityRef<Credits> _Credits;
		
		private EntityRef<Students> _Students;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreditMarkIdChanging(long value);
    partial void OnCreditMarkIdChanged();
    partial void OnStudentIdChanging(long value);
    partial void OnStudentIdChanged();
    partial void OnCreditIdChanging(long value);
    partial void OnCreditIdChanged();
    partial void OnResultChanging(bool value);
    partial void OnResultChanged();
    #endregion
		
		public CreditResults()
		{
			this._Credits = default(EntityRef<Credits>);
			this._Students = default(EntityRef<Students>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditMarkId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CreditMarkId
		{
			get
			{
				return this._CreditMarkId;
			}
			set
			{
				if ((this._CreditMarkId != value))
				{
					this.OnCreditMarkIdChanging(value);
					this.SendPropertyChanging();
					this._CreditMarkId = value;
					this.SendPropertyChanged("CreditMarkId");
					this.OnCreditMarkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="BigInt NOT NULL")]
		public long StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					if (this._Students.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditId", DbType="BigInt NOT NULL")]
		public long CreditId
		{
			get
			{
				return this._CreditId;
			}
			set
			{
				if ((this._CreditId != value))
				{
					if (this._Credits.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreditIdChanging(value);
					this.SendPropertyChanging();
					this._CreditId = value;
					this.SendPropertyChanged("CreditId");
					this.OnCreditIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Bit NOT NULL")]
		public bool Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Credits_CreditResults", Storage="_Credits", ThisKey="CreditId", OtherKey="CreditId", IsForeignKey=true)]
		public Credits Credits
		{
			get
			{
				return this._Credits.Entity;
			}
			set
			{
				Credits previousValue = this._Credits.Entity;
				if (((previousValue != value) 
							|| (this._Credits.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Credits.Entity = null;
						previousValue.CreditResults.Remove(this);
					}
					this._Credits.Entity = value;
					if ((value != null))
					{
						value.CreditResults.Add(this);
						this._CreditId = value.CreditId;
					}
					else
					{
						this._CreditId = default(long);
					}
					this.SendPropertyChanged("Credits");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Students_CreditResults", Storage="_Students", ThisKey="StudentId", OtherKey="StudentId", IsForeignKey=true)]
		public Students Students
		{
			get
			{
				return this._Students.Entity;
			}
			set
			{
				Students previousValue = this._Students.Entity;
				if (((previousValue != value) 
							|| (this._Students.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Students.Entity = null;
						previousValue.CreditResults.Remove(this);
					}
					this._Students.Entity = value;
					if ((value != null))
					{
						value.CreditResults.Add(this);
						this._StudentId = value.StudentId;
					}
					else
					{
						this._StudentId = default(long);
					}
					this.SendPropertyChanged("Students");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamResults")]
	public partial class ExamResults : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ExamMarkId;
		
		private long _StudentId;
		
		private long _ExamId;
		
		private int _Mark;
		
		private EntityRef<Exams> _Exams;
		
		private EntityRef<Students> _Students;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamMarkIdChanging(long value);
    partial void OnExamMarkIdChanged();
    partial void OnStudentIdChanging(long value);
    partial void OnStudentIdChanged();
    partial void OnExamIdChanging(long value);
    partial void OnExamIdChanged();
    partial void OnMarkChanging(int value);
    partial void OnMarkChanged();
    #endregion
		
		public ExamResults()
		{
			this._Exams = default(EntityRef<Exams>);
			this._Students = default(EntityRef<Students>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamMarkId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ExamMarkId
		{
			get
			{
				return this._ExamMarkId;
			}
			set
			{
				if ((this._ExamMarkId != value))
				{
					this.OnExamMarkIdChanging(value);
					this.SendPropertyChanging();
					this._ExamMarkId = value;
					this.SendPropertyChanged("ExamMarkId");
					this.OnExamMarkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="BigInt NOT NULL")]
		public long StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					if (this._Students.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamId", DbType="BigInt NOT NULL")]
		public long ExamId
		{
			get
			{
				return this._ExamId;
			}
			set
			{
				if ((this._ExamId != value))
				{
					if (this._Exams.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExamIdChanging(value);
					this.SendPropertyChanging();
					this._ExamId = value;
					this.SendPropertyChanged("ExamId");
					this.OnExamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int NOT NULL")]
		public int Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this.OnMarkChanging(value);
					this.SendPropertyChanging();
					this._Mark = value;
					this.SendPropertyChanged("Mark");
					this.OnMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Exams_ExamResults", Storage="_Exams", ThisKey="ExamId", OtherKey="ExamId", IsForeignKey=true)]
		public Exams Exams
		{
			get
			{
				return this._Exams.Entity;
			}
			set
			{
				Exams previousValue = this._Exams.Entity;
				if (((previousValue != value) 
							|| (this._Exams.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Exams.Entity = null;
						previousValue.ExamResults.Remove(this);
					}
					this._Exams.Entity = value;
					if ((value != null))
					{
						value.ExamResults.Add(this);
						this._ExamId = value.ExamId;
					}
					else
					{
						this._ExamId = default(long);
					}
					this.SendPropertyChanged("Exams");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Students_ExamResults", Storage="_Students", ThisKey="StudentId", OtherKey="StudentId", IsForeignKey=true)]
		public Students Students
		{
			get
			{
				return this._Students.Entity;
			}
			set
			{
				Students previousValue = this._Students.Entity;
				if (((previousValue != value) 
							|| (this._Students.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Students.Entity = null;
						previousValue.ExamResults.Remove(this);
					}
					this._Students.Entity = value;
					if ((value != null))
					{
						value.ExamResults.Add(this);
						this._StudentId = value.StudentId;
					}
					else
					{
						this._StudentId = default(long);
					}
					this.SendPropertyChanged("Students");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Exams")]
	public partial class Exams : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ExamId;
		
		private long _GroupId;
		
		private long _ProfessorId;
		
		private long _DisciplineId;
		
		private long _SessionId;
		
		private System.DateTime _ExamDate;
		
		private EntitySet<ExamResults> _ExamResults;
		
		private EntityRef<Groups> _Groups;
		
		private EntityRef<Professors> _Professors;
		
		private EntityRef<Disciplines> _Disciplines;
		
		private EntityRef<SessionsInfo> _SessionsInfo;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamIdChanging(long value);
    partial void OnExamIdChanged();
    partial void OnGroupIdChanging(long value);
    partial void OnGroupIdChanged();
    partial void OnProfessorIdChanging(long value);
    partial void OnProfessorIdChanged();
    partial void OnDisciplineIdChanging(long value);
    partial void OnDisciplineIdChanged();
    partial void OnSessionIdChanging(long value);
    partial void OnSessionIdChanged();
    partial void OnExamDateChanging(System.DateTime value);
    partial void OnExamDateChanged();
    #endregion
		
		public Exams()
		{
			this._ExamResults = new EntitySet<ExamResults>(new Action<ExamResults>(this.attach_ExamResults), new Action<ExamResults>(this.detach_ExamResults));
			this._Groups = default(EntityRef<Groups>);
			this._Professors = default(EntityRef<Professors>);
			this._Disciplines = default(EntityRef<Disciplines>);
			this._SessionsInfo = default(EntityRef<SessionsInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ExamId
		{
			get
			{
				return this._ExamId;
			}
			set
			{
				if ((this._ExamId != value))
				{
					this.OnExamIdChanging(value);
					this.SendPropertyChanging();
					this._ExamId = value;
					this.SendPropertyChanged("ExamId");
					this.OnExamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="BigInt NOT NULL")]
		public long GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._Groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorId", DbType="BigInt NOT NULL")]
		public long ProfessorId
		{
			get
			{
				return this._ProfessorId;
			}
			set
			{
				if ((this._ProfessorId != value))
				{
					if (this._Professors.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfessorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessorId = value;
					this.SendPropertyChanged("ProfessorId");
					this.OnProfessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisciplineId", DbType="BigInt NOT NULL")]
		public long DisciplineId
		{
			get
			{
				return this._DisciplineId;
			}
			set
			{
				if ((this._DisciplineId != value))
				{
					if (this._Disciplines.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDisciplineIdChanging(value);
					this.SendPropertyChanging();
					this._DisciplineId = value;
					this.SendPropertyChanged("DisciplineId");
					this.OnDisciplineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionId", DbType="BigInt NOT NULL")]
		public long SessionId
		{
			get
			{
				return this._SessionId;
			}
			set
			{
				if ((this._SessionId != value))
				{
					if (this._SessionsInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSessionIdChanging(value);
					this.SendPropertyChanging();
					this._SessionId = value;
					this.SendPropertyChanged("SessionId");
					this.OnSessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamDate", DbType="DateTime NOT NULL")]
		public System.DateTime ExamDate
		{
			get
			{
				return this._ExamDate;
			}
			set
			{
				if ((this._ExamDate != value))
				{
					this.OnExamDateChanging(value);
					this.SendPropertyChanging();
					this._ExamDate = value;
					this.SendPropertyChanged("ExamDate");
					this.OnExamDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Exams_ExamResults", Storage="_ExamResults", ThisKey="ExamId", OtherKey="ExamId")]
		public EntitySet<ExamResults> ExamResults
		{
			get
			{
				return this._ExamResults;
			}
			set
			{
				this._ExamResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Groups_Exams", Storage="_Groups", ThisKey="GroupId", OtherKey="GroupId", IsForeignKey=true)]
		public Groups Groups
		{
			get
			{
				return this._Groups.Entity;
			}
			set
			{
				Groups previousValue = this._Groups.Entity;
				if (((previousValue != value) 
							|| (this._Groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Groups.Entity = null;
						previousValue.Exams.Remove(this);
					}
					this._Groups.Entity = value;
					if ((value != null))
					{
						value.Exams.Add(this);
						this._GroupId = value.GroupId;
					}
					else
					{
						this._GroupId = default(long);
					}
					this.SendPropertyChanged("Groups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professors_Exams", Storage="_Professors", ThisKey="ProfessorId", OtherKey="ProfessorId", IsForeignKey=true)]
		public Professors Professors
		{
			get
			{
				return this._Professors.Entity;
			}
			set
			{
				Professors previousValue = this._Professors.Entity;
				if (((previousValue != value) 
							|| (this._Professors.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Professors.Entity = null;
						previousValue.Exams.Remove(this);
					}
					this._Professors.Entity = value;
					if ((value != null))
					{
						value.Exams.Add(this);
						this._ProfessorId = value.ProfessorId;
					}
					else
					{
						this._ProfessorId = default(long);
					}
					this.SendPropertyChanged("Professors");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disciplines_Exams", Storage="_Disciplines", ThisKey="DisciplineId", OtherKey="DisciplineId", IsForeignKey=true)]
		public Disciplines Disciplines
		{
			get
			{
				return this._Disciplines.Entity;
			}
			set
			{
				Disciplines previousValue = this._Disciplines.Entity;
				if (((previousValue != value) 
							|| (this._Disciplines.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Disciplines.Entity = null;
						previousValue.Exams.Remove(this);
					}
					this._Disciplines.Entity = value;
					if ((value != null))
					{
						value.Exams.Add(this);
						this._DisciplineId = value.DisciplineId;
					}
					else
					{
						this._DisciplineId = default(long);
					}
					this.SendPropertyChanged("Disciplines");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SessionsInfo_Exams", Storage="_SessionsInfo", ThisKey="SessionId", OtherKey="SessionInfoId", IsForeignKey=true)]
		public SessionsInfo SessionsInfo
		{
			get
			{
				return this._SessionsInfo.Entity;
			}
			set
			{
				SessionsInfo previousValue = this._SessionsInfo.Entity;
				if (((previousValue != value) 
							|| (this._SessionsInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SessionsInfo.Entity = null;
						previousValue.Exams.Remove(this);
					}
					this._SessionsInfo.Entity = value;
					if ((value != null))
					{
						value.Exams.Add(this);
						this._SessionId = value.SessionInfoId;
					}
					else
					{
						this._SessionId = default(long);
					}
					this.SendPropertyChanged("SessionsInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamResults(ExamResults entity)
		{
			this.SendPropertyChanging();
			entity.Exams = this;
		}
		
		private void detach_ExamResults(ExamResults entity)
		{
			this.SendPropertyChanging();
			entity.Exams = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Credits")]
	public partial class Credits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CreditId;
		
		private long _GroupId;
		
		private long _ProfessorId;
		
		private long _DisciplineId;
		
		private long _SessionId;
		
		private System.DateTime _CreditDate;
		
		private EntitySet<CreditResults> _CreditResults;
		
		private EntityRef<Groups> _Groups;
		
		private EntityRef<Professors> _Professors;
		
		private EntityRef<Disciplines> _Disciplines;
		
		private EntityRef<SessionsInfo> _SessionsInfo;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreditIdChanging(long value);
    partial void OnCreditIdChanged();
    partial void OnGroupIdChanging(long value);
    partial void OnGroupIdChanged();
    partial void OnProfessorIdChanging(long value);
    partial void OnProfessorIdChanged();
    partial void OnDisciplineIdChanging(long value);
    partial void OnDisciplineIdChanged();
    partial void OnSessionIdChanging(long value);
    partial void OnSessionIdChanged();
    partial void OnCreditDateChanging(System.DateTime value);
    partial void OnCreditDateChanged();
    #endregion
		
		public Credits()
		{
			this._CreditResults = new EntitySet<CreditResults>(new Action<CreditResults>(this.attach_CreditResults), new Action<CreditResults>(this.detach_CreditResults));
			this._Groups = default(EntityRef<Groups>);
			this._Professors = default(EntityRef<Professors>);
			this._Disciplines = default(EntityRef<Disciplines>);
			this._SessionsInfo = default(EntityRef<SessionsInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CreditId
		{
			get
			{
				return this._CreditId;
			}
			set
			{
				if ((this._CreditId != value))
				{
					this.OnCreditIdChanging(value);
					this.SendPropertyChanging();
					this._CreditId = value;
					this.SendPropertyChanged("CreditId");
					this.OnCreditIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="BigInt NOT NULL")]
		public long GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._Groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorId", DbType="BigInt NOT NULL")]
		public long ProfessorId
		{
			get
			{
				return this._ProfessorId;
			}
			set
			{
				if ((this._ProfessorId != value))
				{
					if (this._Professors.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfessorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessorId = value;
					this.SendPropertyChanged("ProfessorId");
					this.OnProfessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisciplineId", DbType="BigInt NOT NULL")]
		public long DisciplineId
		{
			get
			{
				return this._DisciplineId;
			}
			set
			{
				if ((this._DisciplineId != value))
				{
					if (this._Disciplines.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDisciplineIdChanging(value);
					this.SendPropertyChanging();
					this._DisciplineId = value;
					this.SendPropertyChanged("DisciplineId");
					this.OnDisciplineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionId", DbType="BigInt NOT NULL")]
		public long SessionId
		{
			get
			{
				return this._SessionId;
			}
			set
			{
				if ((this._SessionId != value))
				{
					if (this._SessionsInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSessionIdChanging(value);
					this.SendPropertyChanging();
					this._SessionId = value;
					this.SendPropertyChanged("SessionId");
					this.OnSessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreditDate
		{
			get
			{
				return this._CreditDate;
			}
			set
			{
				if ((this._CreditDate != value))
				{
					this.OnCreditDateChanging(value);
					this.SendPropertyChanging();
					this._CreditDate = value;
					this.SendPropertyChanged("CreditDate");
					this.OnCreditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Credits_CreditResults", Storage="_CreditResults", ThisKey="CreditId", OtherKey="CreditId")]
		public EntitySet<CreditResults> CreditResults
		{
			get
			{
				return this._CreditResults;
			}
			set
			{
				this._CreditResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Groups_Credits", Storage="_Groups", ThisKey="GroupId", OtherKey="GroupId", IsForeignKey=true)]
		public Groups Groups
		{
			get
			{
				return this._Groups.Entity;
			}
			set
			{
				Groups previousValue = this._Groups.Entity;
				if (((previousValue != value) 
							|| (this._Groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Groups.Entity = null;
						previousValue.Credits.Remove(this);
					}
					this._Groups.Entity = value;
					if ((value != null))
					{
						value.Credits.Add(this);
						this._GroupId = value.GroupId;
					}
					else
					{
						this._GroupId = default(long);
					}
					this.SendPropertyChanged("Groups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professors_Credits", Storage="_Professors", ThisKey="ProfessorId", OtherKey="ProfessorId", IsForeignKey=true)]
		public Professors Professors
		{
			get
			{
				return this._Professors.Entity;
			}
			set
			{
				Professors previousValue = this._Professors.Entity;
				if (((previousValue != value) 
							|| (this._Professors.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Professors.Entity = null;
						previousValue.Credits.Remove(this);
					}
					this._Professors.Entity = value;
					if ((value != null))
					{
						value.Credits.Add(this);
						this._ProfessorId = value.ProfessorId;
					}
					else
					{
						this._ProfessorId = default(long);
					}
					this.SendPropertyChanged("Professors");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disciplines_Credits", Storage="_Disciplines", ThisKey="DisciplineId", OtherKey="DisciplineId", IsForeignKey=true)]
		public Disciplines Disciplines
		{
			get
			{
				return this._Disciplines.Entity;
			}
			set
			{
				Disciplines previousValue = this._Disciplines.Entity;
				if (((previousValue != value) 
							|| (this._Disciplines.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Disciplines.Entity = null;
						previousValue.Credits.Remove(this);
					}
					this._Disciplines.Entity = value;
					if ((value != null))
					{
						value.Credits.Add(this);
						this._DisciplineId = value.DisciplineId;
					}
					else
					{
						this._DisciplineId = default(long);
					}
					this.SendPropertyChanged("Disciplines");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SessionsInfo_Credits", Storage="_SessionsInfo", ThisKey="SessionId", OtherKey="SessionInfoId", IsForeignKey=true)]
		public SessionsInfo SessionsInfo
		{
			get
			{
				return this._SessionsInfo.Entity;
			}
			set
			{
				SessionsInfo previousValue = this._SessionsInfo.Entity;
				if (((previousValue != value) 
							|| (this._SessionsInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SessionsInfo.Entity = null;
						previousValue.Credits.Remove(this);
					}
					this._SessionsInfo.Entity = value;
					if ((value != null))
					{
						value.Credits.Add(this);
						this._SessionId = value.SessionInfoId;
					}
					else
					{
						this._SessionId = default(long);
					}
					this.SendPropertyChanged("SessionsInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CreditResults(CreditResults entity)
		{
			this.SendPropertyChanging();
			entity.Credits = this;
		}
		
		private void detach_CreditResults(CreditResults entity)
		{
			this.SendPropertyChanging();
			entity.Credits = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Students")]
	public partial class Students : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _StudentId;
		
		private long _GroupId;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _Patronymic;
		
		private string _Gender;
		
		private System.DateTime _DateOfBirth;
		
		private EntitySet<CreditResults> _CreditResults;
		
		private EntitySet<ExamResults> _ExamResults;
		
		private EntityRef<Groups> _Groups;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIdChanging(long value);
    partial void OnStudentIdChanged();
    partial void OnGroupIdChanging(long value);
    partial void OnGroupIdChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnPatronymicChanging(string value);
    partial void OnPatronymicChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDateOfBirthChanging(System.DateTime value);
    partial void OnDateOfBirthChanged();
    #endregion
		
		public Students()
		{
			this._CreditResults = new EntitySet<CreditResults>(new Action<CreditResults>(this.attach_CreditResults), new Action<CreditResults>(this.detach_CreditResults));
			this._ExamResults = new EntitySet<ExamResults>(new Action<ExamResults>(this.attach_ExamResults), new Action<ExamResults>(this.detach_ExamResults));
			this._Groups = default(EntityRef<Groups>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="BigInt NOT NULL")]
		public long GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._Groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patronymic", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Patronymic
		{
			get
			{
				return this._Patronymic;
			}
			set
			{
				if ((this._Patronymic != value))
				{
					this.OnPatronymicChanging(value);
					this.SendPropertyChanging();
					this._Patronymic = value;
					this.SendPropertyChanged("Patronymic");
					this.OnPatronymicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date NOT NULL")]
		public System.DateTime DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Students_CreditResults", Storage="_CreditResults", ThisKey="StudentId", OtherKey="StudentId")]
		public EntitySet<CreditResults> CreditResults
		{
			get
			{
				return this._CreditResults;
			}
			set
			{
				this._CreditResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Students_ExamResults", Storage="_ExamResults", ThisKey="StudentId", OtherKey="StudentId")]
		public EntitySet<ExamResults> ExamResults
		{
			get
			{
				return this._ExamResults;
			}
			set
			{
				this._ExamResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Groups_Students", Storage="_Groups", ThisKey="GroupId", OtherKey="GroupId", IsForeignKey=true)]
		public Groups Groups
		{
			get
			{
				return this._Groups.Entity;
			}
			set
			{
				Groups previousValue = this._Groups.Entity;
				if (((previousValue != value) 
							|| (this._Groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Groups.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._Groups.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._GroupId = value.GroupId;
					}
					else
					{
						this._GroupId = default(long);
					}
					this.SendPropertyChanged("Groups");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CreditResults(CreditResults entity)
		{
			this.SendPropertyChanging();
			entity.Students = this;
		}
		
		private void detach_CreditResults(CreditResults entity)
		{
			this.SendPropertyChanging();
			entity.Students = null;
		}
		
		private void attach_ExamResults(ExamResults entity)
		{
			this.SendPropertyChanging();
			entity.Students = this;
		}
		
		private void detach_ExamResults(ExamResults entity)
		{
			this.SendPropertyChanging();
			entity.Students = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Groups")]
	public partial class Groups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GroupId;
		
		private string _GroupName;
		
		private EntitySet<Exams> _Exams;
		
		private EntitySet<Credits> _Credits;
		
		private EntitySet<Students> _Students;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIdChanging(long value);
    partial void OnGroupIdChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    #endregion
		
		public Groups()
		{
			this._Exams = new EntitySet<Exams>(new Action<Exams>(this.attach_Exams), new Action<Exams>(this.detach_Exams));
			this._Credits = new EntitySet<Credits>(new Action<Credits>(this.attach_Credits), new Action<Credits>(this.detach_Credits));
			this._Students = new EntitySet<Students>(new Action<Students>(this.attach_Students), new Action<Students>(this.detach_Students));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Groups_Exams", Storage="_Exams", ThisKey="GroupId", OtherKey="GroupId")]
		public EntitySet<Exams> Exams
		{
			get
			{
				return this._Exams;
			}
			set
			{
				this._Exams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Groups_Credits", Storage="_Credits", ThisKey="GroupId", OtherKey="GroupId")]
		public EntitySet<Credits> Credits
		{
			get
			{
				return this._Credits;
			}
			set
			{
				this._Credits.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Groups_Students", Storage="_Students", ThisKey="GroupId", OtherKey="GroupId")]
		public EntitySet<Students> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.Groups = this;
		}
		
		private void detach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.Groups = null;
		}
		
		private void attach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.Groups = this;
		}
		
		private void detach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.Groups = null;
		}
		
		private void attach_Students(Students entity)
		{
			this.SendPropertyChanging();
			entity.Groups = this;
		}
		
		private void detach_Students(Students entity)
		{
			this.SendPropertyChanging();
			entity.Groups = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Professors")]
	public partial class Professors : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ProfessorId;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _Patronymic;
		
		private EntitySet<Exams> _Exams;
		
		private EntitySet<Credits> _Credits;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProfessorIdChanging(long value);
    partial void OnProfessorIdChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnPatronymicChanging(string value);
    partial void OnPatronymicChanged();
    #endregion
		
		public Professors()
		{
			this._Exams = new EntitySet<Exams>(new Action<Exams>(this.attach_Exams), new Action<Exams>(this.detach_Exams));
			this._Credits = new EntitySet<Credits>(new Action<Credits>(this.attach_Credits), new Action<Credits>(this.detach_Credits));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ProfessorId
		{
			get
			{
				return this._ProfessorId;
			}
			set
			{
				if ((this._ProfessorId != value))
				{
					this.OnProfessorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessorId = value;
					this.SendPropertyChanged("ProfessorId");
					this.OnProfessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patronymic", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Patronymic
		{
			get
			{
				return this._Patronymic;
			}
			set
			{
				if ((this._Patronymic != value))
				{
					this.OnPatronymicChanging(value);
					this.SendPropertyChanging();
					this._Patronymic = value;
					this.SendPropertyChanged("Patronymic");
					this.OnPatronymicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professors_Exams", Storage="_Exams", ThisKey="ProfessorId", OtherKey="ProfessorId")]
		public EntitySet<Exams> Exams
		{
			get
			{
				return this._Exams;
			}
			set
			{
				this._Exams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professors_Credits", Storage="_Credits", ThisKey="ProfessorId", OtherKey="ProfessorId")]
		public EntitySet<Credits> Credits
		{
			get
			{
				return this._Credits;
			}
			set
			{
				this._Credits.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.Professors = this;
		}
		
		private void detach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.Professors = null;
		}
		
		private void attach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.Professors = this;
		}
		
		private void detach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.Professors = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Disciplines")]
	public partial class Disciplines : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _DisciplineId;
		
		private string _DisciplineName;
		
		private EntitySet<Exams> _Exams;
		
		private EntitySet<Credits> _Credits;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDisciplineIdChanging(long value);
    partial void OnDisciplineIdChanged();
    partial void OnDisciplineNameChanging(string value);
    partial void OnDisciplineNameChanged();
    #endregion
		
		public Disciplines()
		{
			this._Exams = new EntitySet<Exams>(new Action<Exams>(this.attach_Exams), new Action<Exams>(this.detach_Exams));
			this._Credits = new EntitySet<Credits>(new Action<Credits>(this.attach_Credits), new Action<Credits>(this.detach_Credits));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisciplineId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long DisciplineId
		{
			get
			{
				return this._DisciplineId;
			}
			set
			{
				if ((this._DisciplineId != value))
				{
					this.OnDisciplineIdChanging(value);
					this.SendPropertyChanging();
					this._DisciplineId = value;
					this.SendPropertyChanged("DisciplineId");
					this.OnDisciplineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisciplineName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DisciplineName
		{
			get
			{
				return this._DisciplineName;
			}
			set
			{
				if ((this._DisciplineName != value))
				{
					this.OnDisciplineNameChanging(value);
					this.SendPropertyChanging();
					this._DisciplineName = value;
					this.SendPropertyChanged("DisciplineName");
					this.OnDisciplineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disciplines_Exams", Storage="_Exams", ThisKey="DisciplineId", OtherKey="DisciplineId")]
		public EntitySet<Exams> Exams
		{
			get
			{
				return this._Exams;
			}
			set
			{
				this._Exams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disciplines_Credits", Storage="_Credits", ThisKey="DisciplineId", OtherKey="DisciplineId")]
		public EntitySet<Credits> Credits
		{
			get
			{
				return this._Credits;
			}
			set
			{
				this._Credits.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.Disciplines = this;
		}
		
		private void detach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.Disciplines = null;
		}
		
		private void attach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.Disciplines = this;
		}
		
		private void detach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.Disciplines = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SessionsInfo")]
	public partial class SessionsInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SessionInfoId;
		
		private long _TermNumber;
		
		private long _TermYear;
		
		private EntitySet<Exams> _Exams;
		
		private EntitySet<Credits> _Credits;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSessionInfoIdChanging(long value);
    partial void OnSessionInfoIdChanged();
    partial void OnTermNumberChanging(long value);
    partial void OnTermNumberChanged();
    partial void OnTermYearChanging(long value);
    partial void OnTermYearChanged();
    #endregion
		
		public SessionsInfo()
		{
			this._Exams = new EntitySet<Exams>(new Action<Exams>(this.attach_Exams), new Action<Exams>(this.detach_Exams));
			this._Credits = new EntitySet<Credits>(new Action<Credits>(this.attach_Credits), new Action<Credits>(this.detach_Credits));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionInfoId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long SessionInfoId
		{
			get
			{
				return this._SessionInfoId;
			}
			set
			{
				if ((this._SessionInfoId != value))
				{
					this.OnSessionInfoIdChanging(value);
					this.SendPropertyChanging();
					this._SessionInfoId = value;
					this.SendPropertyChanged("SessionInfoId");
					this.OnSessionInfoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermNumber", DbType="BigInt NOT NULL")]
		public long TermNumber
		{
			get
			{
				return this._TermNumber;
			}
			set
			{
				if ((this._TermNumber != value))
				{
					this.OnTermNumberChanging(value);
					this.SendPropertyChanging();
					this._TermNumber = value;
					this.SendPropertyChanged("TermNumber");
					this.OnTermNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermYear", DbType="BigInt")]
		public long TermYear
		{
			get
			{
				return this._TermYear;
			}
			set
			{
				if ((this._TermYear != value))
				{
					this.OnTermYearChanging(value);
					this.SendPropertyChanging();
					this._TermYear = value;
					this.SendPropertyChanged("TermYear");
					this.OnTermYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SessionsInfo_Exams", Storage="_Exams", ThisKey="SessionInfoId", OtherKey="SessionId")]
		public EntitySet<Exams> Exams
		{
			get
			{
				return this._Exams;
			}
			set
			{
				this._Exams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SessionsInfo_Credits", Storage="_Credits", ThisKey="SessionInfoId", OtherKey="SessionId")]
		public EntitySet<Credits> Credits
		{
			get
			{
				return this._Credits;
			}
			set
			{
				this._Credits.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.SessionsInfo = this;
		}
		
		private void detach_Exams(Exams entity)
		{
			this.SendPropertyChanging();
			entity.SessionsInfo = null;
		}
		
		private void attach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.SessionsInfo = this;
		}
		
		private void detach_Credits(Credits entity)
		{
			this.SendPropertyChanging();
			entity.SessionsInfo = null;
		}
	}
}
#pragma warning restore 1591
